#ifndef SWAGGERANNOTATIONINTERPRETER_GLOBAL_H
#define SWAGGERANNOTATIONINTERPRETER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SWAGGERANNOTATIONINTERPRETER_LIBRARY)
#  define SWAGGERANNOTATIONINTERPRETERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SWAGGERANNOTATIONINTERPRETERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SWAGGERANNOTATIONINTERPRETER_GLOBAL_H
