#ifndef SWAGGERAPI_GLOBAL_H
#define SWAGGERAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SWAGGERAPI_LIBRARY)
#  define SWAGGERAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SWAGGERAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SWAGGERAPI_GLOBAL_H
